version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - attach_workspace:
          at: .
      - run:
          name: list all tests
          command: | 
            pytest --collect-only -q | grep -e "\.py"
      - run:
          name:  Count tests
          command: |
            pytest --collect-only -q | grep -e "\.py" | wc -l
      - run:
          name: Run none
          command: | 
            pytest --last-failed --last-failed-no-failures none || exit 0
      - run:
          name: Run all
          command: |
            if pytest --last-failed --last-failed-no-failures all ; then
              echo 'export TESTS_PASS=true' >> $BASH_ENV
            else
              echo 'export TESTS_PASS=false' >> $BASH_ENV
            fi
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: exit accordingly
          command: |
            if TESTS_PASS=true ; then
              exit 0
            else
              exit 1
            fi

          
workflows:
  sample:
    jobs:
      - build-and-test

# VS Code Extension Version: 1.4.0