version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: list all tests
          command: | 
            pytest --collect-only -q | grep -e "\.py"
      - run:
          name:  Count tests
          command: |
            pytest --collect-only -q | grep -e "\.py" | wc -l
      - run:
          name: Run none
          command: | 
            mkdir test-results
            pytest --last-failed --last-failed-no-failures none
      - run:
          name: Run all
          command: | 
            mkdir test-results
            pytest --last-failed --last-failed-no-failures all
      - store_test_results:
          path: test-results
          
workflows:
  sample:
    jobs:
      - build-and-test

# VS Code Extension Version: 1.4.0